// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA18-fDpY5ZHMLO4bmv3S13SlKiM7JcBJE',
    appId: '1:188610088489:web:6fd0f9c13654f3c61e1638',
    messagingSenderId: '188610088489',
    projectId: 'naraya-hack',
    authDomain: 'naraya-hack.firebaseapp.com',
    storageBucket: 'naraya-hack.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLHWvesOoTVkDkNEbT4TbzF-3aKTVmd4k',
    appId: '1:188610088489:android:e189404dc85543201e1638',
    messagingSenderId: '188610088489',
    projectId: 'naraya-hack',
    storageBucket: 'naraya-hack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwPEHHQ8NDvjWpeoIYalo_IbNB-9TnoSo',
    appId: '1:188610088489:ios:8452d6fa5a45a8861e1638',
    messagingSenderId: '188610088489',
    projectId: 'naraya-hack',
    storageBucket: 'naraya-hack.appspot.com',
    iosClientId: '188610088489-ol7asqvpbbvdrgk2455f9hejbg6pjlhr.apps.googleusercontent.com',
    iosBundleId: 'com.example.narayavisionWeb',
  );
}
